{% set name = "napari-psf-analysis" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_psf_analysis-{{ version }}.tar.gz
  sha256: 02bf62c52ae48d76c6ad0f8c29ab7e6410c66765ccab59a9e6c314c011c8e2b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - python >=3.7
    - scikit-image

test:
  imports:
    - napari_psf_analysis
    - napari_psf_analysis._dock_widget
    - napari_psf_analysis.psf_analysis.PSFAnalysis
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fmi-faim/napari-psf-analysis
  summary: A plugin to analyse point spread functions (PSFs).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tibuch
